#!/bin/bash

URL=$1

if [ $# -ne 1 ]
then
   echo "youku-get URL"
   exit 1
fi


download_episode() {

   local URL=$1
   TMPFILE=`mktemp`
   curl -o $TMPFILE $URL > /dev/null 2>&1
   EPISODE_NAME=`cat $TMPFILE | grep 'span class="name"' | sed "s/^.*<span class=\"name\">//g" | sed "s/<\/span>//g" `

   EPISODE_URL=`echo $URL | sed "s/show_page/show_episode/g"`

   TMPFILE=`mktemp`

   curl -o $TMPFILE $EPISODE_URL >/dev/null 2>&1

   SHOW_URLS=`cat $TMPFILE | grep v_show | sed "s/^.*href=\"//g" | sed "s/?from.*$//g" `


   echo "Downloading into Dir $EPISODE_NAME"
   mkdir $EPISODE_NAME
   cd $EPISODE_NAME

   for SHOW in $SHOW_URLS
   do
      you-get $SHOW
   done  

   rm $TMPFILE

   cd -
}


if [[ $URL =~ "show_page" ]]
then
   download_episode $URL
else
   echo "please use http://www.youku.com/show_page/id_zcc008edc962411de83b1.html kind of URL!!"
   exit 1
fi
